### ISSUE TITLE
cannot chain .rgb()

### ISSUE THREAD

**Issue by ghost** [fknsrs/jetty#1]
Input

```
> tty.bold().sgr(31).text('hello').normal().write('world').rgb(129).rgb([0,0,1],1).text('imissyou');
```

Output

```
helloworldTypeError: Object true has no method 'rgb'
    at repl:1:58
    at REPLServer.self.eval (repl.js:109:21)
    at rli.on.self.bufferedCmd (repl.js:258:20)
    at REPLServer.self.eval (repl.js:116:5)
    at Interface.<anonymous> (repl.js:248:12)
    at Interface.EventEmitter.emit (events.js:96:17)
    at Interface._onLine (readline.js:200:10)
    at Interface._line (readline.js:518:8)
    at Interface._ttyWrite (readline.js:736:14)
    at ReadStream.onkeypress (readline.js:97:10)
> 
```

**Comment by deoxxa** [comment]
.write() returns a boolean value as per the readable stream spec. All is well!
